// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXUFt9quCslB2igyDCjiDke-uk8HVq_oc',
    appId: '1:362419526946:web:6ffe498c5fcaf4fa50997b',
    messagingSenderId: '362419526946',
    projectId: 'circles-social-media',
    authDomain: 'circles-social-media.firebaseapp.com',
    storageBucket: 'circles-social-media.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaGQogrLLdo2zqdfxSrt3LUS2DOVNPs1s',
    appId: '1:362419526946:android:571e3175b408ae2a50997b',
    messagingSenderId: '362419526946',
    projectId: 'circles-social-media',
    storageBucket: 'circles-social-media.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiqB8wuru6Fd3306PC1ur6TqPlUZqcE6c',
    appId: '1:362419526946:ios:c8be96df33e34db950997b',
    messagingSenderId: '362419526946',
    projectId: 'circles-social-media',
    storageBucket: 'circles-social-media.appspot.com',
    iosClientId: '362419526946-8tk78ppv6p0fll0peq95uu8dl6mlmtuc.apps.googleusercontent.com',
    iosBundleId: 'com.example.circles',
  );
}
